ecommerce2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from restaurant.views import ( #restaurant_listview,
                            RestaurantListView,
                            SearchRestaurantListView,
                            # AfricanRestaurantListView,
                            RestaurantDetailView,
                            # restaurant_createview,
                            RestaurantCreateView
                            )

from django.views.generic import TemplateView

# from django.contrib.auth import views as auth_views
# url(r'^accounts/login/$', auth_views.LoginView.as_view()),
from django.contrib.auth.views import LoginView , LogoutView #PasswordResetForm  url(r'^password_reset/$',PasswordResetForm, name="password_reset"),
from menu.views import HomeView

### this is from profile module
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^register/$',RegisterView.as_view(), name="register"),
    url(r'^login/$',LoginView.as_view(), name="login"),
    url(r'^logout/$',LogoutView.as_view(), name="logout"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name="activate"),
    url(r'^profile-follow/$',ProfileFollowToggle.as_view(), name="follow"),
    url(r'^u/', include('profiles.urls', namespace="profiles")),
    url(r'^items/', include('menu.urls', namespace="menu")),
    url(r'^restaurant/', include('restaurant.urls', namespace="restaurant")),
    # url(r'^restaurant/$',  restaurant_listview),
    ## url(r'^restaurant/$',  RestaurantListView.as_view(), name="restaurant"),
    # url(r'^restaurant/create/$',  restaurant_createview), # for the forms
    ## url(r'^restaurant/create/$',  RestaurantCreateView.as_view(), name="restaurant_create"),
    # url(r'^restaurant/(?P<slug>\w+)/$',  SearchRestaurantListView.as_view()),
    # url(r'^restaurant/(?P<rest_id>\w+)/$',  RestaurantDetailView.as_view()),
    ## url(r'^restaurant/(?P<slug>[\w-]+)/$',  RestaurantDetailView.as_view(), name="restaurant_detail"),
    # url(r'^restaurant/african/$',  AfricanRestaurantListView.as_view()),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name="about"),
    url(r'^contact/$', TemplateView.as_view(template_name="contact.html"), name="contact")
]

menu/urls.py
from django.conf.urls import url
from .views import (
                ItemListView,
                ItemDetailView,
                ItemCreateView,
                ItemUpdateView,
)



urlpatterns = [
    url(r'^$',  ItemListView.as_view(), name="list"),
    url(r'^create/$',  ItemCreateView.as_view(), name="create"),
    # url(r'^(?P<pk>\d+)/edit/$',  ItemUpdateView.as_view(), name="edit"),
    # url(r'^(?P<pk>\d+)/$',  ItemDetailView.as_view(), name="detail"),
    url(r'^(?P<pk>\d+)/$',  ItemUpdateView.as_view(), name="detail"),
]

menu/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

from restaurant.models import RestaurantLocation

# Create your models here.

class Item(models.Model):
    # assocaition
    user            = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant      = models.ForeignKey(RestaurantLocation)

    # item stuffs
    name            = models.CharField(max_length=120)
    contents        = models.TextField(help_text="seperate each items by comma")
    excludes        = models.TextField(blank=True, null=True, help_text="seperate each items by comma")
    public          = models.BooleanField(default=True)
    timestap        = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        # return f"/restaurant/{self.slug}"
        return reverse("menu:detail", kwargs={"pk":self.pk})

    class Meta:
        ordering = ['-updated', '-timestap']   #Item.objects.all()

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

menu/forms.py
from django import forms
from .models import Item
from restaurant.models import RestaurantLocation

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public',
        ]

# to handle the change made on ItemCreateView of kwargs
    def __init__(self, user=None, *args, **kwargs):
        # print(kwargs.pop('user'))
        print(user)
        # print(kwargs.pop('instance')) #Item object
        # print(kwargs)
        super(ItemForm, self).__init__(*args, **kwargs)
        # self.fields['restaurant'].queryset = RestaurantLocation.objects.none()
        # self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user, item__isnull=True).exclude(item__isnull=False)
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)

menu/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from .models import Item
from .forms import ItemForm
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView

# Create your views here.
class HomeView(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            return render(request, 'home.html', {})

        user = request.user
        is_following_user_ids = [x.user.id for x in user.is_following.all()]
        # list_
        # for x in user.is_following.all():
        #     list_.append(x.user.id)
        """getting the user items """
        rl = Item.objects.filter(user__id__in=is_following_user_ids, public=True).order_by('-updated')[:3]
        # return render(request, 'menu/home-feed.html', {'rl':rl})  swop rl to object_list for matchin perpose in home-feed.html
        return render(request, 'menu/home-feed.html', {'object_list':rl})


class ItemListView(LoginRequiredMixin, ListView):
    # queryset = Item.objects.all()
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

# COMBINE WITH THE ITEMUPDATEVIEW
class ItemDetailView(LoginRequiredMixin, DetailView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)


class ItemCreateView(LoginRequiredMixin, CreateView):
    template_name = 'form.html'
    form_class = ItemForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        # kwargs['instance'] = Item.objects.filter(user=self.request.user).first()
        # print(kwargs)
        return kwargs

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = "Create Item"
        return context


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    # template_name = 'form.html'
    template_name = 'menu/detail-update.html'
    form_class = ItemForm

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = "Update Item"
        return context

    def get_form_kwargs(self):
        print(self.kwargs)
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        print(kwargs)
        kwargs['user'] = self.request.user
        print(kwargs['user'])
        # kwargs['instance'] = Item.objects.filter(user=self.request.user).first()
        # print(kwargs)
        return kwargs

menu/templates/menu/detail-update.html
{% extends 'base.html' %}

{% block head_title %} {{form.instance.name}} menu items || {{block.super}} {% endblock head_title %}

{% block content %}
    <h1>{{ form.instance.name }}</h1>
    <p>location:{{form.instance.restaurant.location}}</p>
    <p>Restaurant Name:{{form.instance.restaurant}}</p>
    {% if form.instance.contents %}
      content
      <ul>
        {% for item in form.instance.get_contents %}
        <li>{{item}}</li>
        {% endfor %}
      </ul>
    {% endif %}


    {% if form.instance.excludes %}
        excludes
        <ul>
          {% for item in form.instance.get_excludes %}
          <li>{{item}}</li>
          {% endfor %}
        </ul>
    {% endif %}
<hr>
  <h3>Make changes </h3>
  {% include 'snippets/form-snippet.html' with form=form %}

{% endblock %}

menu/templates/menu/home-feed.html
{% extends 'base.html' %}
<!--   EVENTHOUGH IT ISN'T WORKING AT THIS TIME(due to previous debuggs ), THIS IS HOW WE CODE IT TO LIKE IN THE HOME PAGE
        ONLY SHOWING ME <h1>user following feed </h1>
 -->
{% block content %}
  <div class="row">
  <div class="col-sm-6 text-center col-sm-offset-3" >
    <h1>user following feed </h1>
    {% for obj in object_list %}

    <div class="card card-defualt">
      <h3><a href="{% url 'profiles:detail' username=obj.user.username %}">{{obj.user.username}}</a></h3>
      <h4>{{obj.name}}</h4>
      <p>
      <a href="{% url 'profiles:detail' username=obj.user.username %}?q={{obj.restaurant.title}}">{{.obj.restaurant.title}}</a>|
      <a href="{% url 'profiles:detail' username=obj.user.username %}?q={{obj.restaurant.location}}">{{obj.restaurant.location}}</a>|
      <a href="{% url 'profiles:detail' username=obj.user.username %}?q={{obj.restaurant.category}}">{{obj.restaurant.category}}</a>
        <!-- | {{obj.restaurant.location}} | {{obj.restaurant.category}} -->
     </p>
      <p>
      <ul>

          <li style='margin-bottom: 15px;'><b>{{item.name}}</b></li>

             <p> item include:  {{item.contents}} </p>
            <p>item exclude:  {{item.excludes}} </p>

              {% for ing in obj.get_contents %}   <!--why not item.get_contents -->
                <a href="{% url 'profiles:detail' username=obj.user.username %}?q={{ing}}">{{ing}}</a>
              {% endfor %}
      </ul>
      </p>
    </div>

{% endfor %}

</div>
</div>

  {% endblock %}

menu/templates/menu/item_detail.html
<!-- THIS ISN'T IN USE ANYMORE, COMBINED TO DETAIL-UPDATE.HTML -->
{% extends 'base.html' %}

{% block head_title %} menu items || {{block.super}} {% endblock head_title %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <p>location:{{object.restaurant.location}}</p>
    {% if object.contents %}
      content
      <ul>
        {% for item in object.get_contents %}
        <li>{{item}}</li>
        {% endfor %}
      </ul>
    {% endif %}


    {% if object.excludes %}
        excludes
        <ul>
          {% for item in object.get_excludes %}
          <li>{{item}}</li>
          {% endfor %}
        </ul>
    {% endif %}

{% endblock %}

menu/templates/menu/item_list.html
{% extends 'base.html' %}

{% block head_title %} menu items || {{block.super}} {% endblock head_title %}

{% block content %}
    <h1>Menu items <small><a href="{% url 'menu:create' %}">Add</a></small></h1>
    <ul>
      {% for obj in object_list %}
          <li> <a href="{{obj.get_absolute_url}}">{{obj.name}} </a> <br>


            {% if obj.contents  %}
              contents
              <ul>
                {% for item in obj.get_contents %}
                <li>{{item}}</li>
                {% endfor %}
              </ul>
            {% endif %}


            {% if obj.excludes %}
              excludes
              <ul>
                {% for item in obj.get_excludes %}
                <li>{{item}}</li>
                {% endfor %}
              </ul>
          {% endif %}

          </li>
        {% empty %}

        <li><a href="{% url 'menu:create' %}">Add menu item</a></li>
        
      {% endfor %}
    </ul>
{% endblock %}