ecommerce2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from restaurant.views import ( #restaurant_listview,
                            RestaurantListView,
                            SearchRestaurantListView,
                            # AfricanRestaurantListView,
                            RestaurantDetailView,
                            # restaurant_createview,
                            RestaurantCreateView
                            )

from django.views.generic import TemplateView

# from django.contrib.auth import views as auth_views
# url(r'^accounts/login/$', auth_views.LoginView.as_view()),
from django.contrib.auth.views import LoginView , LogoutView #PasswordResetForm  url(r'^password_reset/$',PasswordResetForm, name="password_reset"),
from menu.views import HomeView

### this is from profile module
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', TemplateView.as_view(template_name="home.html"), name="home"),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^register/$',RegisterView.as_view(), name="register"),
    url(r'^login/$',LoginView.as_view(), name="login"),
    url(r'^logout/$',LogoutView.as_view(), name="logout"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name="activate"),
    url(r'^profile-follow/$',ProfileFollowToggle.as_view(), name="follow"),
    url(r'^u/', include('profiles.urls', namespace="profiles")),
    url(r'^items/', include('menu.urls', namespace="menu")),
    url(r'^restaurant/', include('restaurant.urls', namespace="restaurant")),
    # url(r'^restaurant/$',  restaurant_listview),
    ## url(r'^restaurant/$',  RestaurantListView.as_view(), name="restaurant"),
    # url(r'^restaurant/create/$',  restaurant_createview), # for the forms
    ## url(r'^restaurant/create/$',  RestaurantCreateView.as_view(), name="restaurant_create"),
    # url(r'^restaurant/(?P<slug>\w+)/$',  SearchRestaurantListView.as_view()),
    # url(r'^restaurant/(?P<rest_id>\w+)/$',  RestaurantDetailView.as_view()),
    ## url(r'^restaurant/(?P<slug>[\w-]+)/$',  RestaurantDetailView.as_view(), name="restaurant_detail"),
    # url(r'^restaurant/african/$',  AfricanRestaurantListView.as_view()),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name="about"),
    url(r'^contact/$', TemplateView.as_view(template_name="contact.html"), name="contact")
]

menu/urls.py
from django.conf.urls import url
from .views import (
                ItemListView,
                ItemDetailView,
                ItemCreateView,
                ItemUpdateView,
)



urlpatterns = [
    url(r'^$',  ItemListView.as_view(), name="list"),
    url(r'^create/$',  ItemCreateView.as_view(), name="create"),
    # url(r'^(?P<pk>\d+)/edit/$',  ItemUpdateView.as_view(), name="edit"),
    # url(r'^(?P<pk>\d+)/$',  ItemDetailView.as_view(), name="detail"),
    url(r'^(?P<pk>\d+)/$',  ItemUpdateView.as_view(), name="detail"),
]

templates/snippets/css.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

templates/snippets/form-snippet.html
{% if form.errors.non_field_errors %}
   {{form.errors.non_field_errors }}
{% endif %}
<form action="#" method="POST">
  {% csrf_token %}

{{form.as_p}}
  <button type="submit">save</button>
</form>

templates/snippets/js.html
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

templates/snippets/nav.html
<div class="container">
    <a href="{% url "home" %}">home</a>
    <a href="{% url "about" %}">about</a>
    <a href="{% url "contact" %}">contact</a>

    {% if request.user.is_authenticated %}
    <a href="{% url "restaurant:list" %}">restaurant</a>
    <a href="{% url "menu:list" %}">menu items</a>
    {% endif %}

    <a href="/restaurant/american/">restaurantAmerican</a>
    <a href="/restaurant/African/">restaurantAfrican</a>
    <a href="/restaurant/mexican/">restaurantMexican</a>
    <!--ectra -->

</div>

templates/snippets/sidebar.html
<ul>
  <li>items 1</li>
  <li>items 2</li>
  <li>items 3</li>
</ul>